---
name: 'SMB Deploy Action'
description:
  "Automate deploying websites and more to SMB shares with this GitHub action."
author: "Pablo Schmeiser"


inputs:
  smb_server:
    description:
      'The IP address or hostname of the SMB server.'
    required: true
  smb_share:
    description:
      'The name of the SMB share on the server (e.g., "MyFiles").'
    required: true
  smb_username:
    description:
      'The username to authenticate with the SMB server.'
    required: true
  smb_password:
    description:
      'The password for the SMB username. Must be provided via secrets!'
    required: true
  smb_domain:
    description:
      'Optional: The Windows domain name if the SMB server is part of one.'
    required: false
    default: ''
  source_paths:
    description: |
      A space-separated list of file/directory paths
      AND/OR glob patterns to upload (relative to the repository root).
    required: false
    default: '*' # Upload everything from the repo root by default
  destination_path:
    description: |
      The destination path on the SMB share
      (e.g., "/" for root, "/backup/data/").
    required: false
    default: '/' # Upload to the root of the SMB share by default

# NOTE: The 'verbosity' and 'rsync_options' inputs were removed
# as they are not applicable to the smbclient-based approach.

runs:
  using: "composite"
  steps:
    - name: Install SMB Client
      shell: bash
      # 'cifs-utils' is no longer needed, only 'smbclient'
      run: |
        apt-get install -y smbclient

    - name: Upload files using smbclient
      shell: bash
      env:
        SMB_SERVER: ${{ inputs.smb_server }}
        SMB_SHARE: ${{ inputs.smb_share }}
        SMB_USERNAME: ${{ inputs.smb_username }}
        SMB_PASSWORD: ${{ inputs.smb_password }}
        SMB_DOMAIN: ${{ inputs.smb_domain }}
        SOURCE_PATHS: ${{ inputs.source_paths }}
        DESTINATION_PATH: ${{ inputs.destination_path }}
      run: |
        # Construct the full server path for smbclient
        SERVER_PATH="//${SMB_SERVER}/${SMB_SHARE}"

        # Construct credentials string
        CREDENTIALS="-U ${SMB_USERNAME}%${SMB_PASSWORD}"
        if [ -n "$SMB_DOMAIN" ]; then
          CREDENTIALS="${CREDENTIALS} -W ${SMB_DOMAIN}"
        fi

        # Construct smbclient commands
        # 1. 'prompt off': Turn off interactive prompt for mput confirmation.
        # 2. 'recurse on': Enable recursive directory upload.
        # 3. 'cd': Change directory to the remote destination path on the share.
        # 4. 'lcd .': Set the local directory to the current repo root.
        # 5. 'mput': Upload the source_paths list (smbclient handles glob expansion).
        # NOTE: smbclient's 'mput' is basic; it overwrites but doesn't handle deletion
        # or advanced comparison like rsync.

        SMB_COMMANDS="prompt off; recurse on; cd ${DESTINATION_PATH}; lcd .; mput ${SOURCE_PATHS}"

        echo "Connecting to $SERVER_PATH..."
        echo "Executing commands: $SMB_COMMANDS"

        # Execute smbclient
        smbclient "$SERVER_PATH" $CREDENTIALS -c "$SMB_COMMANDS"

branding:
  icon: "upload-cloud"
  color: "white"
